title = "El Saleh Art"
baseURL = "https://el-saleh-art.vercel.app/"
languageCode = "en"
defaultContentLanguage = "en"
enableRobotsTXT = true
timeout = "120s"

[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML"]

[params]
  title = "El Saleh Art"
  description = "Art Gallery"
  author = "El Saleh"
